//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achivment_student
    {
        public int id_achivment { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string text_achivment { get; set; }
        public string form { get; set; }
    
        public virtual student student { get; set; }
    }
}
