//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brothers_sisters
    {
        public int id_num { get; set; }
        public Nullable<int> id_student { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> date_born { get; set; }
        public string status { get; set; }
        public string whois { get; set; }
    
        public virtual student student { get; set; }
    }
}
