//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curators
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curators()
        {
            this.WebSites = new HashSet<WebSites>();
        }
    
        public int id_curator { get; set; }
        public string FIO { get; set; }
        public Nullable<int> id_group { get; set; }
        public string education { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> date_born { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> id_cyclic { get; set; }
        public string email { get; set; }
        public Nullable<int> id_pass { get; set; }
    
        public virtual cyclics cyclics { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Passwords Passwords1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebSites> WebSites { get; set; }
    }
}
