//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorsHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuratorsHelperEntities : DbContext
    {
        public static CuratorsHelperEntities _context;

        public static CuratorsHelperEntities GetContext()
        {
            if (_context == null)
                _context = new CuratorsHelperEntities();
            return _context;
        }

        public CuratorsHelperEntities()
            : base("name=CuratorsHelperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brothers_sisters> Brothers_sisters { get; set; }
        public virtual DbSet<Curators> Curators { get; set; }
        public virtual DbSet<cyclics> cyclics { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Hobbies> Hobbies { get; set; }
        public virtual DbSet<Hostel> Hostel { get; set; }
        public virtual DbSet<Mounth> Mounth { get; set; }
        public virtual DbSet<Parents> Parents { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<Plan_work> Plan_work { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<rukovodstvo> rukovodstvo { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_plan_work> Type_plan_work { get; set; }
        public virtual DbSet<Works_parent> Works_parent { get; set; }
        public virtual DbSet<Works_student> Works_student { get; set; }
        public virtual DbSet<Achivment_student> Achivment_student { get; set; }
        public virtual DbSet<Facts_assotial> Facts_assotial { get; set; }
        public virtual DbSet<Passwords> Passwords { get; set; }
        public virtual DbSet<Student_Hobbies> Student_Hobbies { get; set; }
        public virtual DbSet<WebSites> WebSites { get; set; }
    }
}
