//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parents
    {
        public int id_parent { get; set; }
        public Nullable<int> id_student { get; set; }
        public string FIO { get; set; }
        public string adres { get; set; }
        public string phone { get; set; }
        public string job_place { get; set; }
        public string job { get; set; }
        public Nullable<System.DateTime> date_bord { get; set; }
        public string parent { get; set; }
    
        public virtual student student { get; set; }
    }
}
