//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int id_passport { get; set; }
        public Nullable<int> id_student { get; set; }
        public string num_passport { get; set; }
        public string person_issue { get; set; }
        public Nullable<System.DateTime> date_issue { get; set; }
    
        public virtual student student { get; set; }
    }
}
