//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_work
    {
        public int id_plan { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_type { get; set; }
        public Nullable<int> mounth { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string form_work { get; set; }
        public string check_end { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Mounth Mounth1 { get; set; }
        public virtual Type_plan_work Type_plan_work { get; set; }
    }
}
