//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class rukovodstvo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rukovodstvo()
        {
            this.Groups = new HashSet<Groups>();
        }
    
        public int id_rukovodstva { get; set; }
        public string FIO { get; set; }
        public Nullable<int> id_role { get; set; }
        public string phone { get; set; }
        public byte[] photo { get; set; }
        public string post { get; set; }
        public Nullable<int> id_pass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Groups> Groups { get; set; }
        public virtual roles roles { get; set; }
        public virtual Passwords Passwords1 { get; set; }
    }
}
